#!/bin/bash
# .claude/on-implement-commit.sh
# Called by the post-commit hook on every implement( commit.
# Starts the local dev environment and resets the 60-minute idle timer.
# Generated by claude-workflow — edit commands in claude-workflow.yml.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
TIMESTAMP_FILE="$SCRIPT_DIR/local-env.timestamp"
PID_FILE="$SCRIPT_DIR/local-env.pid"
IDLE_SECONDS=3600

START_CMD="{{local_start_command}}"
DEPLOY_CMD="{{local_deploy_command}}"
STOP_CMD="{{local_stop_command}}"

_write_timestamp() {
    date +%s > "$TIMESTAMP_FILE"
}

_kill_watcher() {
    if [ -f "$PID_FILE" ]; then
        local pid
        pid=$(cat "$PID_FILE")
        if kill -0 "$pid" 2>/dev/null; then
            kill "$pid" 2>/dev/null || true
        fi
        rm -f "$PID_FILE"
    fi
}

_start_watcher() {
    local stop_cmd="$STOP_CMD"
    local timestamp_file="$TIMESTAMP_FILE"
    local pid_file="$PID_FILE"
    local idle_seconds="$IDLE_SECONDS"
    local project_dir="$PROJECT_DIR"

    nohup bash -c "
        while true; do
            sleep 60
            [ -f \"$timestamp_file\" ] || exit 0
            last=\$(cat \"$timestamp_file\")
            now=\$(date +%s)
            age=\$((now - last))
            if [ \$age -gt $idle_seconds ]; then
                echo \"local-env: idle timeout — stopping\"
                cd \"$project_dir\" && $stop_cmd
                rm -f \"$timestamp_file\" \"$pid_file\"
                exit 0
            fi
        done
    " > "$SCRIPT_DIR/local-env.log" 2>&1 &

    echo $! > "$PID_FILE"
    disown $! 2>/dev/null || true
}

case "${1:-deploy}" in
    start)
        if [ -z "$START_CMD" ]; then
            echo "local-env: local_start_command is not set in claude-workflow.yml" >&2
            exit 1
        fi
        echo "local-env: starting..."
        cd "$PROJECT_DIR" && eval "$START_CMD"
        _write_timestamp
        _kill_watcher
        _start_watcher
        echo "local-env: started — auto-stop in 60 minutes"
        ;;

    deploy)
        local_cmd="${DEPLOY_CMD:-$START_CMD}"
        if [ -z "$local_cmd" ]; then
            echo "local-env: local_deploy_command is not set in claude-workflow.yml" >&2
            exit 1
        fi
        echo "local-env: deploying..."
        cd "$PROJECT_DIR" && eval "$local_cmd"
        _write_timestamp
        _kill_watcher
        _start_watcher
        echo "local-env: deployed — timer reset to 60 minutes"
        ;;

    stop)
        if [ -z "$STOP_CMD" ]; then
            echo "local-env: local_stop_command is not set in claude-workflow.yml" >&2
            exit 1
        fi
        echo "local-env: stopping..."
        _kill_watcher
        cd "$PROJECT_DIR" && eval "$STOP_CMD"
        rm -f "$TIMESTAMP_FILE"
        echo "local-env: stopped"
        ;;

    status)
        if [ ! -f "$TIMESTAMP_FILE" ]; then
            echo "local-env: stopped"
        else
            last=$(cat "$TIMESTAMP_FILE")
            now=$(date +%s)
            elapsed=$(( (now - last) / 60 ))
            remaining=$(( (IDLE_SECONDS - (now - last)) / 60 ))
            if [ $remaining -le 0 ]; then
                echo "local-env: timer expired (stopping soon)"
            else
                echo "local-env: running — ${elapsed}m elapsed, ~${remaining}m remaining"
            fi
        fi
        ;;

    *)
        echo "Usage: on-implement-commit.sh <start|deploy|stop|status>"
        exit 1
        ;;
esac
