#!/bin/bash
# .claude/on-verify-trigger.sh
# Called by the post-commit hook when a plan moves to verify state.
# Launches a background Claude session to run the verify agent.
# Generated by claude-workflow — do not edit manually.

set -euo pipefail

PLAN_NAME="${1:?Usage: on-verify-trigger.sh <plan-name>}"
ROOT=$(git rev-parse --show-toplevel)
PLAN_ID=$(echo "$PLAN_NAME" | grep -o 'PLN-[0-9]*')
LOG_DIR="$ROOT/.claude"
LOG="$LOG_DIR/verify-${PLAN_NAME}.log"

# Avoid duplicate runs — check if a verify session is already running for this plan
PIDFILE="$LOG_DIR/verify-${PLAN_NAME}.pid"
if [ -f "$PIDFILE" ]; then
    old_pid=$(cat "$PIDFILE")
    if kill -0 "$old_pid" 2>/dev/null; then
        echo "verify-trigger: already running for $PLAN_NAME (PID $old_pid)" >&2
        exit 0
    fi
    rm -f "$PIDFILE"
fi

echo "verify-trigger: launching verify agent for $PLAN_NAME"

nohup bash -c "
    cd \"$ROOT\"
    claude -p \
        --model sonnet \
        --permission-mode auto \
        \"You are the autonomous verify agent. Read .claude/skills/wf-verify/SKILL.md for your full instructions, then execute them for plan $PLAN_ID (full name: $PLAN_NAME).\"
    rm -f \"$PIDFILE\"
" > "$LOG" 2>&1 &

echo $! > "$PIDFILE"
disown $! 2>/dev/null || true

echo "verify-trigger: agent PID $! — log at $LOG"
