#!/bin/bash
# .claude/on-verify-trigger.sh
# Called by the post-commit hook when a plan moves to verify state.
# Generated by claude-workflow — do not edit manually.
#
# This is now a thin shim over wf-spawn.sh, which is the single spawn path for
# every unattended worker. That matters: the pidfile guard, model selection,
# logging and event trail all live in one place, so the post-commit hook and
# the orchestrator daemon cannot double-launch the same plan.
#
# The hook is the low-latency nudge; the daemon's sweep is the safety net that
# catches anything the hook missed.

set -euo pipefail

PLAN_NAME="${1:?Usage: on-verify-trigger.sh <plan-name>}"
ROOT=$(git rev-parse --show-toplevel)

exec "$ROOT/scripts/wf-exec.sh" wf-spawn.sh verify "$PLAN_NAME"
